num1=input("Enter Number One\n")
num2=input("Enter Number Two\n")
num1=int(num1)
num2=int(num2)
print(num1+num2)
print(num1*num2)
print(num1-num2)
print(num1/num2)
print(type(num1))
print(type(num2))
