name="raJesH"
name1=name.capitalize()
name2=name.upper()
print(name)
print(name1)
print(name2)
print(id(name2))
name3=name2.lower()
print(id(name))
print(name3)
name5=name.swapcase()
print(name5)
print(id(name5))
rww="1Rghaj2"
print(rww)
rww="Kusham"
print(rww)
t1="vlaue"
t2="kamrI"
print(t1.upper())
print(t2.capitalize())
print(len(t2))