char1="Rajeshwari"
print(char1[1:3])
print(r'c:\c\path\name')
print(len(char1))
num4=max(1,2,3,22,33,11,87)
print(num4)
num5=min(4,3,-1,-11,-345)
print(num5)
num7='432sdfsd'
print(num7)
no1=input("Enter a number for which you need a table")
no1=int(no1)
print(no1*1, end="\n")
print(no1*2, end="\n")
print(no1*3, end="\n")
print(no1*4, end="\n")
print(no1*5, end="\n")
print(no1*6, end="\n")
print(no1*7, end="\n")
print(no1*8, end="\n")
print(no1*9, end="\n")
print(no1*10, end="\n")


num1=input("Enter your first number\n")
num2=input("Enter your second number\n")
num3=input("Enter   third number\n")
num1=int(num1)
num2=int(num2)
num3=int(num3)
print("This is addition of your entered number",num1+num2+num3, sep=" ", end="\n")
print("This is minus of your entered number",num1-num2-num3, sep=" ", end="\n")
print("This is division of your entered number",num1/num2/num3, sep=" ", end="\n")
print("This is multiply of your entered number",num1*num2*num3, sep=" ", end="\n")
print(num1+num2)
